# Generated by Django 5.0.6 on 2024-06-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0003_kgmodel_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='kgmodel',
            name='langchainfilter',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
