# Generated by Django 5.0.6 on 2024-06-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0009_rule_alter_faq_options_alter_history_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knowledgegraph',
            old_name='langchainfilter',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='knowledgegraph',
            name='rule',
            field=models.CharField(choices=[('filter', 'For Filtering'), ('route', 'For Routing / Ask to Who')], max_length=100),
        ),
    ]
