# Generated by Django 5.0.6 on 2024-06-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0012_remove_faq_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgegraph',
            name='owner',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
