# Generated by Django 5.0.6 on 2024-06-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0002_kgmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='kgmodel',
            name='rule',
            field=models.CharField(choices=[('scope', 'For Scoping'), ('route', 'For Routing / Ask to Who')], default='scope', max_length=100),
            preserve_default=False,
        ),
    ]
