# Generated by Django 5.0.6 on 2024-06-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0004_kgmodel_langchainfilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kgmodel',
            name='json',
            field=models.CharField(max_length=100),
        ),
    ]
