# Generated by Django 5.0.6 on 2024-06-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0006_alter_kgmodel_json_alter_kgmodel_langchainfilter'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='FAQModel',
            new_name='FAQ',
        ),
        migrations.RenameModel(
            old_name='KGModel',
            new_name='KnowledgeGraph',
        ),
    ]
